/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author ross
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        txt_psswrd = new javax.swing.JPasswordField();
        uno = new javax.swing.JLabel();
        dos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_Aceptar1 = new rsbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(null);

        label1.setBackground(new java.awt.Color(58, 90, 182));
        label1.setForeground(new java.awt.Color(16, 110, 229));
        jPanel1.add(label1);
        label1.setBounds(0, 0, 270, 400);

        txt_psswrd.setForeground(new java.awt.Color(197, 197, 197));
        txt_psswrd.setText("jPasswordField1");
        txt_psswrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_psswrdMouseClicked(evt);
            }
        });
        jPanel1.add(txt_psswrd);
        txt_psswrd.setBounds(410, 240, 220, 28);

        uno.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        uno.setText("Usuario");
        jPanel1.add(uno);
        uno.setBounds(410, 110, 60, 20);

        dos.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        dos.setText("Contraseña");
        jPanel1.add(dos);
        dos.setBounds(410, 210, 90, 16);

        jLabel3.setFont(new java.awt.Font("Phetsarath OT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(146, 146, 146));
        jLabel3.setText("Iniciar Sesión ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 40, 180, 40);

        txt_usuario.setForeground(new java.awt.Color(183, 183, 183));
        txt_usuario.setText("Usuario");
        jPanel1.add(txt_usuario);
        txt_usuario.setBounds(410, 150, 220, 28);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/accountUno.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 140, 50, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/close.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(680, 10, 20, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/lockDos.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(360, 220, 40, 50);

        btn_Aceptar1.setText("Ingresar");
        btn_Aceptar1.setColorNormal(new java.awt.Color(73, 116, 239));
        btn_Aceptar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Aceptar1MouseClicked(evt);
            }
        });
        btn_Aceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Aceptar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Aceptar1);
        btn_Aceptar1.setBounds(460, 300, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_psswrdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_psswrdMouseClicked
        // TODO add your handling code here:

        txt_psswrd.setText("");
    }//GEN-LAST:event_txt_psswrdMouseClicked

    private void btn_Aceptar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Aceptar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Aceptar1MouseClicked

    private void btn_Aceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Aceptar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Aceptar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btn_Aceptar1;
    private javax.swing.JLabel dos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private javax.swing.JPasswordField txt_psswrd;
    private javax.swing.JTextField txt_usuario;
    private javax.swing.JLabel uno;
    // End of variables declaration//GEN-END:variables
}
